CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    github_url TEXT,
    linkedin_url TEXT,
    twitter_url TEXT,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);