BEGIN;

    CREATE TABLE projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    creator_id INTEGER REFERENCES users
    (id) ON
    DELETE CASCADE NOT NULL,
    description TEXT
    NOT NULL,
    tags TEXT ARRAY,
    live_url TEXT,
    trello_url TEXT,
    github_url TEXT,
    date_created TIMESTAMPTZ DEFAULT now
    () NOT NULL
);

CREATE TABLE vacancies (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id INTEGER REFERENCES projects
(id) ON
DELETE CASCADE NOT NULL,
    user_id INTEGER
REFERENCES users
(id) ON
DELETE
SET NULL
,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    skills TEXT ARRAY,
    date_created TIMESTAMPTZ DEFAULT now
() NOT NULL
);

COMMIT;