BEGIN;

CREATE TYPE request_status AS ENUM (
    'pending',
    'approved',
    'denied'
);

CREATE TABLE requests (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vacancies_id INTEGER REFERENCES vacancies(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    status request_status DEFAULT 'pending' NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMIT;