BEGIN;

CREATE TYPE notification_type AS ENUM (
    'join',
    'leave',
    'post',
    'chat'
);

CREATE TABLE notifications (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipient_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE NOT NULL,
    type notification_type NOT NULL,
    seen BOOLEAN DEFAULT FALSE,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

COMMIT;